In [1]:
import numpy as np

In [5]:
data = np.loadtxt(r"C:\\Users\\DELL\Downloads\\fit.txt", dtype='str')
data

array([['06-10-2017', '5464', 'Neutral', '181', '5', 'Inactive'],
       ['07-10-2017', '6041', 'Sad', '197', '8', 'Inactive'],
       ['08-10-2017', '25', 'Sad', '0', '5', 'Inactive'],
       ['09-10-2017', '5461', 'Sad', '174', '4', 'Inactive'],
       ['10-10-2017', '6915', 'Neutral', '223', '5', 'Active'],
       ['11-10-2017', '4545', 'Sad', '149', '6', 'Inactive'],
       ['12-10-2017', '4340', 'Sad', '140', '6', 'Inactive'],
       ['13-10-2017', '1230', 'Sad', '38', '7', 'Inactive'],
       ['14-10-2017', '61', 'Sad', '1', '5', 'Inactive'],
       ['15-10-2017', '1258', 'Sad', '40', '6', 'Inactive'],
       ['16-10-2017', '3148', 'Sad', '101', '8', 'Inactive'],
       ['17-10-2017', '4687', 'Sad', '152', '5', 'Inactive'],
       ['18-10-2017', '4732', 'Happy', '150', '6', 'Active'],
       ['19-10-2017', '3519', 'Sad', '113', '7', 'Inactive'],
       ['20-10-2017', '1580', 'Sad', '49', '5', 'Inactive'],
       ['21-10-2017', '2822', 'Sad', '86', '6', 'Inactive'],
       ['22-10

In [6]:
data.shape

(96, 6)

In [7]:
data.size

576

In [8]:
data.ndim

2

In [9]:
data[0]

array(['06-10-2017', '5464', 'Neutral', '181', '5', 'Inactive'],
      dtype='<U10')

In [12]:
data[1][:5]

array(['07-10-2017', '6041', 'Sad', '197', '8'], dtype='<U10')

In [13]:
# Tranposing the  data
data = data.T
data

array([['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
        '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
        '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
        '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
        '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
        '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
        '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
        '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
        '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
        '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
        '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
        '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
        '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
        '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
        '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
        '05-12-2017', '06-12-2017', '07-

In [16]:
step_count = data[1].astype('int')
step_count

array([5464, 6041,   25, 5461, 6915, 4545, 4340, 1230,   61, 1258, 3148,
       4687, 4732, 3519, 1580, 2822,  181, 3158, 4383, 3881, 4037,  202,
        292,  330, 2209, 4550, 4435, 4779, 1831, 2255,  539, 5464, 6041,
       4068, 4683, 4033, 6314,  614, 3149, 4005, 4880, 4136,  705,  570,
        269, 4275, 5999, 4421, 6930, 5195,  546,  493,  995, 1163, 6676,
       3608,  774, 1421, 4064, 2725, 5934, 1867, 3721, 2374, 2909, 1648,
        799, 7102, 3941, 7422,  437, 1231, 1696, 4921,  221, 6500, 3575,
       4061,  651,  753,  518, 5537, 4108, 5376, 3066,  177,   36,  299,
       1447, 2599,  702,  133,  153,  500, 2127, 2203])

In [17]:
step_count.mean()

2935.9375

In [18]:
np.median(step_count)

2987.5

In [22]:
step_count.min()

25

In [23]:
step_count.max()

7422

In [24]:
step_count.std()

2132.191887728154

In [26]:
step_count[step_count > step_count.mean()].size

48

In [27]:
step_count[step_count > 5000].size

17

In [28]:
step_count[step_count > 4000].size

38

In [29]:
step_count.size

96

In [30]:
step_count[step_count > 6000].size

9

In [31]:
step_count[step_count > 7000].size

2

In [32]:
step_count[step_count > 2000].size

57

In [33]:
step_count[step_count < 100]

array([25, 61, 36])

In [34]:
step_count[step_count < 1000].size

28

In [35]:
step_count.size

96

In [38]:
step_count[(step_count >1000) & (step_count <= 2000)].size

11

In [39]:
step_count[(step_count >2000) & (step_count <= 3000)].size

9

In [40]:
step_count[(step_count >3000) & (step_count <= 4000)].size

10

In [41]:
step_count[(step_count >4000) & (step_count <= 5000)].size

21

In [42]:
step_count[(step_count >5000) & (step_count <= 6000)].size

8

In [43]:
step_count[(step_count >6000) & (step_count <= 7000)].size

7

In [44]:
step_count[step_count >7000].size

2

In [45]:
data[2]

array(['Neutral', 'Sad', 'Sad', 'Sad', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Sad', 'Sad', 'Sad', 'Happy', 'Sad', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral',
       'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Neutral',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Sad', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Sad', 'Neutral', 'Neutral',
       'Sad', 'Sad', 'Neutral', 'Neutral', 'Happy', 'Neutral', 'Neutral',
       'Sad', 'Neutral', 'Sad', 'Neutral', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Happy', 'Neutral', 'Happy', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Sad', 'Sad', 'Happy', 'Neutral', 'Neutral',
       'Happy'], dtype='<U10')

In [46]:
mood = data[2]

In [47]:
mood[:5]

array(['Neutral', 'Sad', 'Sad', 'Sad', 'Neutral'], dtype='<U10')

In [48]:
unique_values = np.unique(mood)
unique_values

array(['Happy', 'Neutral', 'Sad'], dtype='<U10')

In [50]:
mood=='Happy'

array([False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False,  True, False,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
       False,  True,  True,  True,  True,  True,  True,  True, False,
       False, False, False, False, False, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
        True, False,  True, False, False, False, False, False, False,
       False, False,  True, False, False,  True])

In [51]:
mood[mood=='Happy'].size

40

In [52]:
mood[mood=='Neutral'].size

27

In [53]:
mood[mood=='Sad'].size

29

In [54]:
40+27+29

96

In [55]:
data[3][:5]

array(['181', '197', '0', '174', '223'], dtype='<U10')

In [56]:
data[3]

array(['181', '197', '0', '174', '223', '149', '140', '38', '1', '40',
       '101', '152', '150', '113', '49', '86', '6', '99', '143', '125',
       '129', '6', '9', '10', '72', '150', '141', '156', '57', '72', '17',
       '181', '197', '131', '154', '137', '193', '19', '101', '139',
       '164', '137', '22', '17', '9', '145', '192', '146', '234', '167',
       '16', '17', '32', '35', '220', '116', '23', '44', '131', '86',
       '194', '60', '121', '76', '93', '53', '25', '227', '125', '243',
       '14', '39', '55', '158', '7', '213', '116', '129', '21', '28',
       '16', '180', '138', '176', '99', '5', '1', '10', '47', '84', '23',
       '4', '0', '0', '0', '0'], dtype='<U10')

In [57]:
cal_burnt = data[3].astype('int')
cal_burnt

array([181, 197,   0, 174, 223, 149, 140,  38,   1,  40, 101, 152, 150,
       113,  49,  86,   6,  99, 143, 125, 129,   6,   9,  10,  72, 150,
       141, 156,  57,  72,  17, 181, 197, 131, 154, 137, 193,  19, 101,
       139, 164, 137,  22,  17,   9, 145, 192, 146, 234, 167,  16,  17,
        32,  35, 220, 116,  23,  44, 131,  86, 194,  60, 121,  76,  93,
        53,  25, 227, 125, 243,  14,  39,  55, 158,   7, 213, 116, 129,
        21,  28,  16, 180, 138, 176,  99,   5,   1,  10,  47,  84,  23,
         4,   0,   0,   0,   0])

In [58]:
cal_burnt.max()

243

In [59]:
cal_burnt.min()

0

In [60]:
cal_burnt.mean()

93.44791666666667

In [62]:
cal_burnt.sum()/cal_burnt.size

93.44791666666667

In [64]:
np.unique(cal_burnt).size

72

In [65]:
data[:5]

array([['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
        '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
        '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
        '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
        '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
        '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
        '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
        '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
        '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
        '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
        '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
        '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
        '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
        '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
        '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
        '05-12-2017', '06-12-2017', '07-

In [67]:
data[4]

array(['5', '8', '5', '4', '5', '6', '6', '7', '5', '6', '8', '5', '6',
       '7', '5', '6', '8', '5', '4', '5', '6', '8', '5', '6', '5', '8',
       '5', '4', '5', '4', '5', '4', '3', '2', '9', '5', '6', '4', '5',
       '8', '4', '5', '6', '5', '6', '5', '6', '5', '6', '5', '6', '7',
       '6', '7', '6', '5', '6', '7', '8', '8', '7', '8', '5', '4', '3',
       '3', '4', '5', '5', '5', '3', '4', '4', '5', '5', '5', '5', '5',
       '5', '4', '3', '4', '5', '5', '4', '5', '3', '3', '3', '2', '3',
       '2', '8', '5', '5', '5'], dtype='<U10')

In [70]:
hours_slept = data[4].astype('int')

In [71]:
hours_slept.min()

2

In [72]:
hours_slept.max()

9

In [73]:
hours_slept.mean()

5.21875

In [74]:
hours_slept.sum()/hours_slept.size

5.21875

In [76]:
hours_slept.sum()/hours_slept.shape[0]

5.21875

In [77]:
hours_slept.sum()/len(hours_slept)

5.21875

In [78]:
hours_slept.sum()

501

In [79]:
hours_slept.size

96

In [80]:
hours_slept[90]

3

In [81]:
hours_slept[95]

5